from django.urls import path
from django.views.generic import TemplateView, RedirectView
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about", TemplateView.as_view(template_name="about.html"), name="about"),
    path("contact", views.contact, name="contact"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("settings", views.settings, name="settings"),
    path("signup", views.signup, name="signup"),
    path("signin", views.signin, name="signin"),
    path("logout", views.logout, name="logout"),
    path("profile/<int:id>", views.profile, name="profile"),
    path("profile/<int:id>/update", views.profile_update, name="profile.update"),
    path("location", views.location_index, name="location.index"),
    path("location/create", views.location_create, name="location.create"),
    path("location/<int:id>/edit", views.location_edit, name="location.edit"),
    path("location/<int:id>/delete", views.location_delete, name="location.delete"),
    path("location/<int:id>", views.location_show, name="location.show"),
    path("supplier", views.supplier_index, name="supplier.index"),
    path("supplier/create", views.supplier_create, name="supplier.create"),
    path("supplier/<int:id>/edit", views.supplier_edit, name="supplier.edit"),
    path("supplier/<int:id>/delete", views.supplier_delete, name="supplier.delete"),
    path("supplier/<int:id>", views.supplier_show, name="supplier.show"),
    path("product", views.product_index, name="product.index"),
    path("product/create", views.product_create, name="product.create"),
    path("product/<int:id>/edit", views.product_edit, name="product.edit"),
    path("product/<int:id>/delete", views.product_delete, name="product.delete"),
    path("product/<int:id>", views.product_show, name="product.show"),
    path("order", views.order_index, name="order.index"),
    path("order/create", views.order_create, name="order.create"),
    path("order/<int:id>/edit", views.order_edit, name="order.edit"),
    path("order/<int:id>/delete", views.order_delete, name="order.delete"),
    path("order/<int:id>", views.order_show, name="order.show"),
    path("comment", views.comment_index, name="comment.index"),
    path("comment/create", views.comment_create, name="comment.create"),
    path("comment/<int:id>/edit", views.comment_edit, name="comment.edit"),
    path("comment/<int:id>/delete", views.comment_delete, name="comment.delete"),
    path("comment/<int:id>", views.comment_show, name="comment.show"),
    # path("buyer", views.buyer_index, name="buyer.index"),
    # path("buyer/create", views.buyer_create, name="buyer.create"),
    # path("buyer/<int:id>/edit", views.buyer_edit, name="buyer.edit"),
    # path("buyer/<int:id>/delete", views.buyer_delete, name="buyer.delete"),
    # path("buyer/<int:id>", views.buyer_show, name="buyer.show"),
    # path("guarantee", views.guarantee_index, name="guarantee.index"),
    # path("guarantee/create", views.guarantee_create, name="guarantee.create"),
    # path("guarantee/<int:id>/edit", views.guarantee_edit, name="guarantee.edit"),
    # path("guarantee/<int:id>/delete", views.guarantee_delete, name="guarantee.delete"),
    # path("guarantee/<int:id>", views.guarantee_show, name="guarantee.show"),
    # path("insurance", views.insurance_index, name="insurance.index"),
    # path("insurance/create", views.insurance_create, name="insurance.create"),
    # path("insurance/<int:id>/edit", views.insurance_edit, name="insurance.edit"),
    # path("insurance/<int:id>/delete", views.insurance_delete, name="insurance.delete"),
    # path("insurance/<int:id>", views.insurance_show, name="insurance.show"),
]
