from django.urls import path
from django.views.generic import TemplateView, RedirectView
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about", TemplateView.as_view(template_name="about.html"), name="about"),
    path("contact", views.contact, name="contact"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("settings", views.settings, name="settings"),
    path("signup", views.signup, name="signup"),
    path("signin", views.signin, name="signin"),
    path("logout", views.logout, name="logout"),
    path("profile/<int:id>", views.profile, name="profile"),
    path("profile/<int:id>/update", views.profile_update, name="profile.update"),
    path("location", views.location_index, name="location.index"),
    path("location/create", views.location_create, name="location.create"),
    path("location/<int:id>/edit", views.location_edit, name="location.edit"),
    path("location/<int:id>/delete", views.location_delete, name="location.delete"),
    path("location/<int:id>", views.location_show, name="location.show"),
    path("product", views.product_index, name="product.index"),
    path("product/create", views.product_create, name="product.create"),
    path("product/<int:id>/edit", views.product_edit, name="product.edit"),
    path("product/<int:id>/delete", views.product_delete, name="product.delete"),
    path("product/<int:id>", views.product_show, name="product.show"),
    path("order", views.order_index, name="order.index"),
    path("order/create", views.order_create, name="order.create"),
    path("order/<int:id>/edit", views.order_edit, name="order.edit"),
    path("order/<int:id>/delete", views.order_delete, name="order.delete"),
    path("order/<int:id>", views.order_show, name="order.show"),
    path("comment", views.comment_index, name="comment.index"),
    path("comment/create", views.comment_create, name="comment.create"),
    path("comment/<int:id>/edit", views.comment_edit, name="comment.edit"),
    path("comment/<int:id>/delete", views.comment_delete, name="comment.delete"),
    path("comment/<int:id>", views.comment_show, name="comment.show"),
]
