# Generated by Django 4.0.6 on 2022-08-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
    ]
