# Generated by Django 4.0.6 on 2022-10-10 04:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bool', 'bool'), ('date', 'date'), ('input', 'input'), ('text', 'text'), ('number', 'number'), ('select', 'select')], default='input', max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('choice', models.CharField(max_length=200)),
                ('width', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.form')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.questionfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
