# Generated by Django 4.0.6 on 2022-11-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
