# Generated by Django 4.0.6 on 2022-10-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfield',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
