# Generated by Django 4.0.6 on 2022-10-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_questionfield_is_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfield',
            name='type',
            field=models.CharField(choices=[('boolean', 'boolean'), ('date', 'date'), ('long-text', 'long-text'), ('text', 'text'), ('number', 'number'), ('select', 'select')], default='text', max_length=200),
        ),
    ]
