# Generated by Django 4.0.6 on 2022-08-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
    ]
