# Generated by Django 4.1.3 on 2023-01-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="main.buyer"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="location",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.location",
            ),
        ),
    ]
