# Generated by Django 4.0.6 on 2022-08-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.RemoveField(
            model_name='service',
            name='link',
        ),
    ]
