# Generated by Django 4.0.6 on 2022-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
