# Generated by Django 4.0.6 on 2022-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale_service', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
