# Generated by Django 4.0.6 on 2022-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale_service', '0004_service_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
