# Generated by Django 4.0.6 on 2022-11-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale_service', '0005_partner_facebook_partner_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='tags',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='partners',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True),
        ),
    ]
