# Generated by Django 4.0.6 on 2022-11-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale_service', '0006_alter_partner_tags_alter_product_partners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
