# Generated by Django 4.0.6 on 2022-11-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale_service', '0007_alter_partner_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='twitter',
        ),
    ]
